# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAcct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('email_acct', models.CharField(max_length=1000)),
                ('password', models.CharField(max_length=100)),
                ('validation_code', models.IntegerField(null=True)),
                ('is_validated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=200, null=True)),
                ('last', models.CharField(max_length=200, null=True)),
                ('join_date', models.DateField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='build_profile.User')),
            ],
        ),
        migrations.AddField(
            model_name='emailacct',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='build_profile.User'),
        ),
    ]
