# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 23:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('build_profile', '0003_auto_20170725_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_validated',
            new_name='email_is_validated',
        ),
        migrations.RemoveField(
            model_name='user',
            name='validation_code',
        ),
    ]
