# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 01:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('build_profile', '0004_auto_20170727_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_acct', models.CharField(max_length=1000, null=True)),
                ('validation_key', models.CharField(max_length=1000)),
                ('email_is_validated', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_is_validated',
        ),
        migrations.AddField(
            model_name='email',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='build_profile.User'),
        ),
    ]
