# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 03:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('build_profile', '0005_auto_20170728_0130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='validation_key',
        ),
    ]
